services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env 
    networks:
      - golang-rest-api

networks:
  golang-rest-api:
    driver: bridge
