server:
  port: 8080
  host: localhost

database:
  host:     ""     # จะถูก override จาก env
  port:     0      # same
  user:     ""     # same
  password: ""     # same
  dbname:   ""     # same
  sslmode:  ""     # same
